# Generated by Django 3.2.8 on 2022-01-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TheStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='coveredbridge04.jpg', upload_to='statusImgs')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='occApp.status')),
            ],
        ),
        migrations.CreateModel(
            name='TheRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='coveredbridge04.jpg', upload_to='roleImgs')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='occApp.role')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True)),
                ('liveLink', models.CharField(max_length=255)),
                ('sourceCode', models.CharField(max_length=255)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projStatus', to='occApp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=255)),
                ('lastName', models.CharField(blank=True, max_length=255)),
                ('brigadeEmail', models.CharField(blank=True, max_length=255)),
                ('personalEmail', models.CharField(blank=True, max_length=255)),
                ('linkedIn', models.CharField(blank=True, max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberRole', to='occApp.role')),
            ],
        ),
    ]
