# Generated by Django 3.2.8 on 2022-01-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='liveLink',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='sourceCode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
